### ISSUE TITLE
Unable to Login in getpos

### ISSUE THREAD

**Issue by Mohtashim-1** [nestorbird/GETPOS#45]
![Image](https://github.com/user-attachments/assets/73fe95a1-9b2c-47f3-b1b7-7c752becd511)

**Comment by hamzahabeeb** [comment]
> ![Image](https://github.com/user-attachments/assets/73fe95a1-9b2c-47f3-b1b7-7c752becd511)

Hi, was this resolved for you?

**Comment by hamzahabeeb** [comment]
This issue was resolved. YOu have to generate api kets in user doctype

**Comment by Mohtashim-1** [comment]
> > ![Image](https://github.com/user-attachments/assets/73fe95a1-9b2c-47f3-b1b7-7c752becd511)
> 
> Hi, was this resolved for you?

No issue not resolved this yet i generated the api now what should i had to do can you please guide me
